# Colours
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
LIGHTSKYBLUE = 'lightskyblue3'

# FilePath
SCORE_FONT_FILEPATH = 'Helvetica.ttf'
POKEMON_FONT_FILEPATH = "Pokemon_GB.ttf"
SUBOLEYA_FONT_FILEPATH = "SuboleyaRegular.ttf"
START_GAME_FONT_FILEPATH = "Pokemon_GB.ttf"
INSTRUCTION_TITLE_FONT_FILEPATH = "SuboleyaRegular.ttf"
INSTRUCTION_TEXT_FONT_FILEPATH = "SuboleyaRegular.ttf"

GAME_BACKGROUND_MUSIC_FILEPATH = "rolla_costa.mp3"
GAME_OVER_MUSIC_FILEPATH = "game_over.wav"
COLLECT_BOOK_FILEPATH = "collect_books.wav"
COLLECT_OBSTACLE_FILEPATH = "negative-beeps.wav"
MOVEMENT_MUSIC_FILE_PATH = "movement.mp3"

MAIN_CHARACTER_FILEPATH = "MAIN_CHAR.PNG"
BOOK_FILEPATH = "books.png"
OBSTACLE_FILEPATH = "obstacle.PNG"
LOADING_BAR_BOARDER_FILEPATH = "Loading_Bar_Background-removebg-preview.png"
LOADING_BAR_FILEPATH = "Loading_Bar.png"

INTRO_BACKGROUND_IMAGE_FILEPATH = "intro_bg.png"
GAME_BACKGROUND_IMAGE_FILEPATH = "library_bg.jpg"
GAME_OVER_BACKGROUND_FILEPATH = "no_signal.jpg"
LOGIN_BACKGROUND_FILEPATH = "NUS.jpg"
STUN_IMAGE_FILEPATH1 = "stun_image_1.PNG"
STUN_IMAGE_FILEPATH2 = "stun_image_2.PNG"
LEADERBOARD_BACKGROUND_FILEPATH = "leaderboard_bg.png"
LEADERBOARD_FILEPATH = "leaderboard_info.txt"

# Game related
FPS = 60
STUN_ANIMATION_SPEED = 0.4
GAME_WIDTH, GAME_HEIGHT = 600, 660
MAIN_CHARACTER_IMAGE_WIDTH, MAIN_CHARACTER_IMAGE_HEIGHT = 180, 180
MAIN_CHARACTER_RECT_WIDTH, MAIN_CHARACTER_RECT_HEIGHT = 150, 180
GAME_CAPTION = "YSC2221 Project: Game"
BOOK_IMAGE_WIDTH, BOOK_IMAGE_HEIGHT = 80, 80
OBSTACLE_IMAGE_WIDTH, OBSTACLE_IMAGE_HEIGHT = 100, 90
DROP_RECT_WIDTH, DROP_RECT_HEIGHT = 80, 80
MAX_TIME_LIMIT = 15000
CENTRE_PILLAR_WIDTH = 10
CENTRE_PILLAR_Y = 0
SCORE_FONT_SIZE = 30
GAME_OVER_FONT_SIZE = 40
LEFT_SIDE = GAME_WIDTH // 2 - CENTRE_PILLAR_WIDTH - DROP_RECT_WIDTH
RIGHT_SIDE = GAME_WIDTH // 2
INITIAL_MAIN_CHARACTER_X = GAME_WIDTH // 2 - CENTRE_PILLAR_WIDTH -\
    MAIN_CHARACTER_RECT_WIDTH
INITIAL_MAIN_CHARACTER_Y = GAME_HEIGHT - MAIN_CHARACTER_RECT_HEIGHT
INITIAL_INVISIBLE_X = GAME_WIDTH // 2
INITIAL_DROP_Y = 0
DROP_UPDATE_DISTANCE = 80
OBSTACLE_RNG_VALUE = 0
BOOK_RNG_VALUE = 1
GAME_OVER_TEXT = "GAME OVER :'("
LEFT_RNG_VALUE = 0
RIGHT_RNG_VALUE = 1
DROP_PADDING = 0
SCORE_TEXT = "SCORE: "
SCORE_PADDING = 10
LOADING_BAR_WIDTH = 100
LOADING_BAR_HEIGHT = 20
LOADING_BAR_X = 10
LOADING_BAR_Y = 10
LOADING_BAR_PADDING = 6
GAME_RESTART_TEXT = "Press space to play again!"
GAME_RESTART_FONT_SIZE = 15

TIER_1_SCORE = 500
TIER_1_TIME = 1000
TIER_2_SCORE = 1000
TIER_2_TIME = 500
TIER_3_SCORE = 1500
TIER_3_TIME = 250
TIER_4_SCORE = 2000
TIER_4_TIME = 120
TIER_5_SCORE = 2500
TIER_5_SCORE = 50
BACKGROUND_IMAGE_X = 0
BACKGROUND_IMAGE_Y = 0
STUN_DURATION = 500
STUN_IMAGE_WIDTH = MAIN_CHARACTER_IMAGE_WIDTH
STUN_IMAGE_HEIGHT = MAIN_CHARACTER_IMAGE_HEIGHT
SCORE_INCREMENT = 100

# login related
default_username = "RandomNUStudent"
MAX_LENGTH_USERNAME = 13
INPUT_X = GAME_WIDTH//2 - 200
INPUT_Y = GAME_HEIGHT//2
INPUT_WIDTH = 350
INPUT_HEIGHT = 32
INPUT_FONT_STYLE = None
INPUT_FONT = 40
INPUT_BOX_WIDTH = 2
INPUT_PROMPT = "Enter your Student ID:"
INPUT_PROMPT_X = GAME_WIDTH//2 - 200
INPUT_PROMPT_Y = GAME_HEIGHT//2 - INPUT_HEIGHT
GAME_TITLE_TOP = "Help Me"
GAME_TITLE_TOP_X = GAME_WIDTH//2 - 230
GAME_TITLE_TOP_Y = GAME_HEIGHT//2 - 7*INPUT_HEIGHT
Game_TITLE_BOTTOM = "Study"
GAME_TITLE_BOTTOM_X = GAME_WIDTH//2 - 200
GAME_TITLE_BOTTOM_Y = GAME_HEIGHT//2 - 4*INPUT_HEIGHT
TITLE_FONT_SIZE = 70

# Instruction related
INSTRUCTION_TITLE = "Instructions"
INSTRUCTION_TITLE_FONT_SIZE = 40
INSTRUCTION_TEXT_1 = "Help your friend be productive and collect the books!"
INSTRUCTION_TEXT_2 = "Avoid the Phones because they will distract you !!"
INSTRUCTION_TEXT_3 = "Press Left/Right to collect objects"
START_GAME = "Press space to start the game"
INSTRUCTION_TEXT_SIZE = 25
START_GAME_SIZE = 15
INSTRUCTION_TITLE_Y = 30
INSTRUCTION_TEXT_X = 50
INSTRUCTION_TEXT_Y = 100
GAME_START_Y = 200

# Leaderboard related
LEADERBOARD_TEXT = "Press L to see the leaderboard"
LEADERBOARD_TITLE = "Dean's List"
LEADERBOARD_SIZE = 10
LEADERBOARD_INDEX_X = 0
LEADERBOARD_NAME_X = 75
LEADERBOARD_SCORE_X = 400
LEADERBOARD_TITLE_Y = 0
EXIT_LEADERBOARD_TEXT = "Press Esc to go back"
LEADERBOARD_NAME_FONT_SIZE = 40
LEADERBOARD_TITLE_FONT_SIZE = 40
GAME_RETURN_FONT_SIZE = 15
TEXT_HEIGHT = 2
